### ISSUE TITLE
Upgrade hive 2.3.5 -> 2.3.7

### ISSUE THREAD

**Issue by meneal** [IBM/docker-hive#14]
Hive 2.3.5 no longer exists here: `https://www-us.apache.org/dist/hive/hive-2.3.5/apache-hive-2.3.5-bin.tar.gz`

**Comment by meneal** [comment]
As far as I can tell, this does not require an upgrade to `hadoop` from the current `hadoop-2.9.2`.

**Comment by meneal** [comment]
Current available versions listed here: https://downloads.apache.org/hive/

**Comment by meneal** [comment]
This issue was raised in error. Current version in repo is `3.1.2`

**Comment by meneal** [comment]
This is required for the hive2/hadoop2 image.

**Comment by shawnzhu** [comment]
fixed by https://github.com/IBM/docker-hive/commit/501eefb864d4adb5ab6d4d21f63978058a237469
