### ISSUE TITLE
Hive not installed in base image

### ISSUE THREAD

**Issue by meneal** [IBM/docker-hive#2]
### Expectation

No errors when running `docker build .`, and then `docker run -it <container_id> /bin/sh`

### Actual

`bin/hive: line 354: ps: command not found`

### Diganotstic

[Stretch does not include ps by default.](https://github.com/debuerreotype/debuerreotype/issues/14#issuecomment-311820232).

**Comment by shawnzhu** [comment]
I can dig more about why it reports `ps: command not found` since I got this all the time but it doesn't impact runtime.

it reminds me we need Travis CI for this repo to make sure Hive is installed as expected

**Comment by shawnzhu** [comment]
This successful build indicates that all test cases pass which means Hive is installed successfully: https://github.com/IBM/docker-hive/runs/150123019
